"""cambio del id entero en facultades a str debido a la decision de usar la abreviacion como identificador unico 

Revision ID: 735c570c5277
Revises: d3d9f76cbd5a
Create Date: 2024-09-23 10:37:40.711292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735c570c5277'
down_revision: Union[str, None] = 'd3d9f76cbd5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
