"""cambio del id entero en facultades a str debido a la decision de usar la abreviacion como identificador unico 

Revision ID: d3d9f76cbd5a
Revises: 8f9f80211a01
Create Date: 2024-09-23 10:32:35.160367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d9f76cbd5a'
down_revision: Union[str, None] = '8f9f80211a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
